baseURL = 'https://thanh-0dev.github.io/hugo-framework/'
languageCode = 'en-us'
title = "Thanh-Long's Hugo Discovery"
theme = 'PaperMod'
[params]
  [assets]
    favicon = "/favicon.ico"
    favicon16x16 = "/favicon-16x16.png"
    favicon32x32 = "/favicon-32x32.png"
    apple_touch_icon = "/apple-touch-icon.png"